---
# tasks file for final-role
- include_vars: /root/ansible/final-role/vars/varsforrole.yml

#install dependencies
- name: Install dependencies
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - docker
    - nslookup
    - dig

- name: Start services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - git
    - docker
    - nslookup
    - dig

#add user admin
- name: Create admin user with password
  ansible.builtin.user:
    name: admin
    password: Bsmch@500K!

- name: Make admin user an admin 4real
  ansible.builtin.shell: usermod -aG wheel admin

#Disable root authentication
- name: Disable root ssh authentication
  lineinfile:
        dest: /etc/ssh/sshd_cofig
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"

#Turn on firewall and selinux
- name: Turn on firewalld
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - firewalld

- name: Turn on Selinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing


#NFS Mount
- name: install dependencies for nfs mount
  ansible.builtin.yum:
    name:
      - nfs-utils
      - nfs4-acl-tools
    state: present

- name: Create a mountpoint if it does not exist
  ansible.builtin.file:
    path: {{ mountpoint }}
    state: directory

- name: mount nfs share
  ansible.posix.mount:
    src: "{{ nfssrc }}"
    path: "{{ mountpoint }}"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs

#Increase open files limit to 50000
- name: Increase open files limit to 50000
  ansible.posix.sysctl:
    name: fs.file-max
    value: '50000'
    state: present
    reload: yes

#Increase tcp-buffer allowed open ports range - 1024 to 65000
- name: Increase tcp-buffer allowed open ports range - 1024 to 65000
  ansible.posix.sysctl:
    name: net.ipv4.ip_local_port_range
    value: '1024 65000'
    state: present
    reload: yes

#Increase tcp-buffer read write memory limit to 2mb
- name: Increase tcp-buffer read write memory limit to 2mb
  ansible.posix.sysctl:
    - name: "{{ item }}"
      value: '2000000'
      state: present
      reload: yes
  with_items:
    - net.core.wmem_max
    - net.core.rmem_max
    - net.core.rmem_default
    - net.core.wmem_default
